services:
  coconut_web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
volumes:
  mysql_data:
    driver: local